### ISSUE TITLE
week 4 exercise ready for review

### ISSUE THREAD

**Issue by ctkrause** [ctkrause/IndieProjectCalebKrause#1]
@pawaitemadisoncollege - week 4 exercise is ready for review. I put the screenshot in the images folder.

1. What were your key learning points/takeaways?
Key learning points were reinforcement of hibernate implementation and techniques. Had to be very analytical and add the dependencies, then the config, and proceed from there. Very easy to miss something in this process, having only done it one other time, and having my hand held via the demo videos at that. 
2. What challenged you?
I kind of forgot the process for making that other database for testing. I tried to just make another table in the same database before remembering that we create an entirely separate db. My code to modify existing database entries wasn't working and that was just more trial and error than anything. 
3. What problems did you solve and what resources did you use to solve them?
Probably the biggest issue is switching back and forth between all your resources, java classes, and database info. It's nice being able to pop that database tab out, but I'm still getting used to having SO MUCH going on within one IDE. Really didn't have a ton of issues implementing this since the demo code for the week 3 stuff is pretty similar. It was just a lot of tweaking to get things working with my database and my whatnot.

**Comment by pawaitemadisoncollege** [comment]
I think this is a good summary of what a lot of ent java is "_Had to be very analytical and add the dependencies, then the config, and proceed from there. Very easy to miss something in this process_", @ctkrause.  So many of the technologies we use in this class depend on a lot of picky configurat-y stuff: maven, log4j, hibernate, authentication/authorization, aws. If something config isn't quite right, things won't work and the errors won't necessary indicate exactly what exactly is wrong. 

Glad to see you implemented this in your indie project! The entity, Dao and tests look good.  

One thing - verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(newUser.equals(insertedUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/ctkrause/IndieProjectCalebKrause/blob/e4a9dcbe1c47d9f3ab1e2501f5d724e54cceac36/src/main/test/java/persistence/UserDaoTest.java#L52

Keep the momentum going!
