### ISSUE TITLE
Indie Project Ready For Checkpoint 2

### ISSUE THREAD

**Issue by ctkrause** [ctkrause/IndieProjectCalebKrause#6]
@pawaitemadisoncollege - Indie Project is ready for checkpoint 2. You will need to jump into the "GenericDao" branch, as I branched off before implementing to that. May soon need to merge back into my main, but that's for another day. Planning on adding some more logging statements as I go, but I've mostly been using them for debug and removing them once I solve the issue. WakaTime is very helpful for time log! Keep forgetting to update that dang thing. Two entities/daos are fully unit tested, just need to add for the "jobs" table, which may still change a little bit. Cheers.

**Comment by pawaitemadisoncollege** [comment]
All that hard work is really paying off; things are looking very good here!  I think you are close on checkpoint 3 too.

- [ ] Would be nice to see the completed items in the Project Plan check off using `- [x]` see how this renders below
- [x] a completed item, for example
- [ ] use log statement for the stack traces too: 
![Screen Shot 2021-03-08 at 11 32 48 AM](https://user-images.githubusercontent.com/13874466/110358479-12e1a600-8002-11eb-8fee-f3af9f19ad14.png). You can do this with code something like: log.error("Your pretty message here here", exception);  I also think the log statements in the screenshot above should be error rather than debug. 

Nice work using branches too :)
